### ISSUE TITLE
Any plan to test maskrcnn with spinenet backbone?

### ISSUE THREAD

**Issue by ousinkou** [yan-roo/SpineNet-Pytorch#2]
Greate work!  I found only retinanet is tested. Have any plan to test maskrcnn with spinenet backbone?

**Comment by yan-roo** [comment]
@ousinkou Thanks. I'll try to do some experiment on maskrcnn with mmdetection.
If your have any updates or implementation, I'm willing to help you testing.

**Comment by ousinkou** [comment]
@yan-roo OK, Thanks. I will try my best.

**Comment by yan-roo** [comment]
@ousinkou  Thanks for your inspiration. Mask R-CNN SpineNet-49S version is available. Others are still training.
