### ISSUE TITLE
Model evaluation 

### ISSUE THREAD

**Issue by rosapiotr** [yan-roo/SpineNet-Pytorch#7]
Hey,
I want to check mAP of the model during training and after it finishes. For this purpose I use --validate during training and tools/test.py script after that. The output I get looks like this:
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.384
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.614
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.439
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.059
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.147
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.436
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.005
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.049
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.426
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.104
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.173
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.483

My problem is that there is far more objects on images than 100. I changed the **max_per_img** in config file so now the model outputs more bounding boxes, but when calculating mAP, maxDets is still set to 100. Is there a way to easily change this number?

**Comment by yan-roo** [comment]
Hello @rosapiotr 

https://github.com/open-mmlab/mmdetection/issues/1641

`proposal` is used for evaluating the performance of proposals, e.g., recall.
`bbox` is used for evaluating the performance of final bbox results, e.g., mAP.

------------------------------------------------------------------------------------------
Method 1:
You can modify the config
https://github.com/yan-roo/SpineNet-Pytorch/blob/master/configs/spinenet/spinenet_49S_B_8gpu.py#L104
from `evaluation = dict(interval=1, metric='bbox')`
to  `evaluation = dict(interval=1, metric='proposal')`

same as 
`python tools/test.py ${CONFIG_FILE} ${CHECKPOINT_FILE} --eval proposal`

------------------------------------------------------------------------------------------

Method 2:
You have to modify mmdetection/mmdet/datasets/coco.py or your customized dataset
Add `cocoEval.params.maxDets = [1, 10, 1000]` to line 360
```
cocoEval = COCOeval(cocoGt, cocoDt, iou_type)
cocoEval.params.maxDets = [1, 10, 1000]
cocoEval.params.imgIds = self.img_ids
```

**Comment by rosapiotr** [comment]
Worked perfectly, thank you!
